### ISSUE TITLE
Introduce "useVisitorData" hook

### ISSUE THREAD

**Issue by TheUnderScorer** [fingerprintjs/fingerprintjs-pro-react-native#10]
I'm wondering if we could introduce a similar hook as we have in https://github.com/fingerprintjs/fingerprintjs-pro-react for this package as well? 

Something like this:
```typescript
import {useVisitorData} from '@fingerprintjs/fingerprintjs-pro-react-native';

  const {
    isLoading,
    error,
    data,
  } = useVisitorData('PUBLIC_API_KEY', 'REGION');
```

I believe that it would provide a better developer experience, and make it more consistent with our react library. 
To keep the consistency we can also omit the parameters here, and add a provider as well.

Things to consider:
* would we also want to use the @fingerprintjs/fingerprintjs-pro-spa for caching?
* maybe in order to avoid duplicating the code, we can use the logic from https://github.com/fingerprintjs/fingerprintjs-pro-react, while providing custom agent implementation, in order to use the native libraries under the hood?

WDYT?

**Comment by ilfa** [comment]
Hook added in v1.0.0
