### ISSUE TITLE
NetworkError: Could not connect to the server.

### ISSUE THREAD

**Issue by adnxy** [fingerprintjs/fingerprintjs-pro-react-native#101]
FingerprintJS is throwing network connection issues reported by our monitoring tool for both iOS & Android apps. There are multiple instances of this error, and it's throwing different error messages:

**NetworkError: A server with the specified hostname could not be found.**

**NetworkError: Could not connect to the server.**

**NetworkError: The Internet connection appears to be offline.**

Note: my fingerprintjs-pro-react-native is 2.5.3

Did anyone experienced something similar?

**Comment by JuroUhlar** [comment]
Hi @adnxy! 

Does the issue happen to all Fingerprint requests or just occasionally? Wouldn't a small percentage of this kind of error be expected if some of your users are interacting with your application using unstable network connections?

Are you using some kind of proxy integration between your application and Fingerprint? Some VPN providers might block access to our APIs on a DNS level. If users are accessing your application using a VPN, they might run into these kinds of errors. Using a [custom subdomain setup](https://dev.fingerprint.com/docs/custom-subdomain-setup) or a [cloud proxy integration](https://dev.fingerprint.com/docs/integrations) would resolve that issue.
