### ISSUE TITLE
Version being set in dist file is 2.7.0

### ISSUE THREAD

**Issue by fluz-jeff** [fingerprintjs/fingerprintjs-pro-react-native#109]
I've spun up a completely bare-bones repo with just node v20 and installed the latest fingerprintjs-pro-react-native package - https://github.com/fluz-jeff/fingerprintjs/blob/633e3cb98469c86cdf3fda4a1734a4e8179f5130/package.json#L12.

You can see the version defined in the `dist` directory is set as 2.7.0 - https://github.com/fluz-jeff/fingerprintjs/blob/633e3cb98469c86cdf3fda4a1734a4e8179f5130/node_modules/%40fingerprintjs/fingerprintjs-pro-react-native/dist/fpjs-pro-react-native.cjs.js#L341

**Comment by ilfa** [comment]
Hi @fluz-jeff!
Thank you for noticing this problem, looks like we missed something in the release pipeline.
We will fix it soon.
