### ISSUE TITLE
Introduce E2E tests

### ISSUE THREAD

**Issue by TheUnderScorer** [fingerprintjs/fingerprintjs-pro-react-native#11]
It might be a little bit far stretched, but I'm wondering if we should introduce some E2E tests for our library? 
As far as I see, we don't have any tests yet.

Since we are using native modules under the hood, unit tests won't make much sense here. We could use https://github.com/wix/detox/ for it, and add tests to the **TestProject** - even simple checking like if the `visitorId` is being rendered.

WDYT?

**Comment by necipallef** [comment]
This is planned and will be addressed. Closing
