### ISSUE TITLE
Apple Privacy Manifests

### ISSUE THREAD

**Issue by grgmo** [fingerprintjs/fingerprintjs-pro-react-native#117]
Apple's requirement to document usages of certain Api's is coming into effect May 1.
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

using scanner tool ([here](https://github.com/Wooder/ios_17_required_reason_api_scanner)) to scan for usages of these API's/symbols

and there are a couple of results found for `FingerprintPro`:

```
NSFileSystemFreeSize
NSFileSystemSize
```

Is this something the team is aware of? or have an ETA for?

more info here
https://github.com/react-native-community/discussions-and-proposals/discussions/776

**Edit**
looks like ios sdk got the update https://github.com/fingerprintjs/fingerprintjs-pro-ios/releases/tag/2.3.2

**Comment by makma** [comment]
Hey @grgmo, I confirmed with the team that by using the latest version of this project and [following the installation of dependencies ](https://github.com/fingerprintjs/fingerprintjs-pro-react-native?tab=readme-ov-file#2-configure-native-dependencies) the changes from the https://github.com/fingerprintjs/fingerprintjs-pro-ios/releases/tag/2.3.2, will be automatically propagated to your app.

**Comment by grgmo** [comment]
awesome, happy to close this. Will re-open if any issues.
