### ISSUE TITLE
Error "FailedError: bad request" is returned when calling getVisitorData

### ISSUE THREAD

**Issue by chochihim** [fingerprintjs/fingerprintjs-pro-react-native#119]
As titled. It has been working flawlessly until recently one of our users reported problem. One major difference between that problematic user and other working users is that the problematic user has recently updated his iPhone to iOS 18 beta. I wonder if it causes the error.

**Comment by makma** [comment]
Thanks @chochihim for reporting this, we'll try to reproduce on our side and will let you know.

**Comment by makma** [comment]
Hello @chochihim,
The team owning the underlying iOS SDK has been already aware of this issue. They are fixing it right now.

**Comment by makma** [comment]
Hey @chochihim,
The issue was fixed and should be resolved without any steps necessary on your side. Please, feel free to reopen this issue if you continue encountering this behavior.
