### ISSUE TITLE
Google play Requires Prominent App Disclosure for using the useVisitorData hook

### ISSUE THREAD

**Issue by wardjk87** [fingerprintjs/fingerprintjs-pro-react-native#132]
Our app uses version 3.1.0 and calls useVisitorData when our app initializes, in order to prevent fraud in our app. Recently we got the following correspondence from Google Play, stating that our app would be removed from the store unless we provide a prominent app disclosure inside our app:

"Your app is uploading users' Installed application information to https://api.fpjs.io/ without a prominent disclosure.
As per Google Play’s [User Data] [link](https://notifications.google.com/g/p/ANiao5qr0haxzNAF_J5Ink0x3bABkv23x1M7DeYgVumxeYW3KmKuRp7JJr2PMyY3G09u1H9RIhL-ST4Y-vD7jmfI5qe6pA_AMooc2gWE-FwlxeZeSb6O_np0Z8yvvHdzoQ0ttAyS2MqcHgYDArfp2D6E2_HKU_PaJ68Vs7NYw7g2QPRHJRiha5o2vzIaxIPV4zzaSGW9MmbdBlbb4ojcv5zbevfQacWj8rD-zXre4AyVcLTLfAeYDaZ81YW0C95k5u3xbHObPc9ROHQU)

In cases where your app’s access, collection, use, or sharing of personal and sensitive user data may not be within the reasonable expectation of the user of the product or feature in question, you must provide an in-app disclosure of your data access, collection, use, and sharing and seek affirmative user consent."

We found no instructions for compliance with Google Play in order to user this paid plugin service. The documentation should include how to resolve compliance, in order to be able to use the plugin on an app released via Google Play.

**Comment by wardjk87** [comment]
![rejection-notice](https://github.com/user-attachments/assets/90ac803d-abba-4209-8511-edcb0b21f55b)

**Comment by ilfa** [comment]
Hello @wardjk87,

Thank you for the issue. We are aware of this problem and already working on the solution. We are going to stop collecting the inventory of installed apps from user devices.

We are planning to release this fix to the [Android agent](https://github.com/fingerprintjs/fingerprintjs-pro-android) first and then we will update the agent version in the React Native SDK. We are planning to do it at the beginning of October.

**Comment by wardjk87** [comment]
@ilfa Thank you for your prompt communication and feedback. Since we do not want our app to be delisted, is there an alternative solution other than to remove the SDK? For example, downgrading? We only have until Sept 30 to comply or appeal.

**Comment by ilfa** [comment]
@wardjk87 let me ask my colleagues about the exact ETA for the Android Agent release. (As I remember, you can even update it as a peer dependency without waiting for a new version of the RN SDK.)

**Comment by ilfa** [comment]
Hello @wardjk87!

I appreciate your patience. We couldn't guarantee a new release before September 30th, but I discussed available options with my team.
1. You could add a prominent disclosure that the list of installed apps is collected and shared with a 3rd party vendor.
2. If you use the library only for identification, you could downgrade to React Native SDK [v2.2.0](https://github.com/fingerprintjs/fingerprintjs-pro-react-native/releases/tag/v2.2.0) and lower (to have Android SDK version lower than v2.3.0).
If you use smart signals let us know which, and we could check if they were supported in this version.
[Here](https://github.com/fingerprintjs/fingerprintjs-pro-react-native/releases/tag/v3.0.0) you can check the reasons for the major release v3.0.0, looks like it shouldn't be a problem to downgrade.

**Comment by wardjk87** [comment]
@ilfa We have investigated v2.2.0, and it looks like we don't need to refactor our front end code. On the backend, we pass the visitor ID, and we use the following enforcement options to determine fraud: suspect score, vpn, ip geolocation, and bot detection. We are going to test out our integration to see if we find any issues, and then we will submit a new version to Google Play.

**Comment by ilfa** [comment]
@wardjk87 VPN detection is significantly worse in this version, other signals are presented with the same quality.

I'll let you know as soon as we release a new version with the fix.

**Comment by wardjk87** [comment]
@ilfa We successfully released a version of our app with v2.2.0 of fingerprint, and so far Google has indicated we are compliant. Thanks for guidance. We will update the fingerprint version once a compatible version is available that does not require an in app disclosure.
