### ISSUE TITLE
Get error when use react native new architecture 

### ISSUE THREAD

**Issue by weifpeng** [fingerprintjs/fingerprintjs-pro-react-native#134]
Dear author,
I wanted to reach out and kindly request if you could consider updating the library to support React Native's new architecture, specifically by implementing JSI (JavaScript Interface) support. Currently, we will get error when upgrade to 0.75
![image](https://github.com/user-attachments/assets/db3f053a-c325-465d-9e8f-d5e3960df130)

**Comment by necipallef** [comment]
Hi @weifpeng! Thanks for letting us know about this.

I first would like to point out that the SDK performs as expected with the default React Native v0.75 setup. The problem you are facing is strictly related to the New Architecture as you mentioned.

We don't have any immediate plans to support New Architecture of React Native that makes use of JSI but we acknowledge that it is important. We will make plans to address this, please stay tuned.
