### ISSUE TITLE
does this work with expo?

### ISSUE THREAD

**Issue by djixadin** [fingerprintjs/fingerprintjs-pro-react-native#65]
basically title. i was trying to implement it, following the example too and this error is all i am getting 
```
RNFingerprintjsPro init error:  [TypeError: null is not an object (evaluating 'reactNative.NativeModules.RNFingerprintjsPro.init')] 

```

**Comment by djixadin** [comment]
just saw in limitations that it doesnt

**Comment by makma** [comment]
Hello @djixadin, expo is not supported right now, as you noticed, it's also mentioned in the [limitations](https://dev.fingerprint.com/docs/fingerprintjs-pro-react-native#limitations). Nevertheless, if it's something crucial for you, I think we could investigate it at some point.
