### ISSUE TITLE
@fingerprintjs/fingerprintjs-pro-react-native 2.5.1 npm doesn't contain build folder 

### ISSUE THREAD

**Issue by litinskii** [fingerprintjs/fingerprintjs-pro-react-native#93]
<img width="814" alt="image" src="https://github.com/fingerprintjs/fingerprintjs-pro-react-native/assets/10028441/7e6c4f37-e419-4d87-adb9-873a888df960">

**Comment by ilfa** [comment]
@litinskii thank you for the issue!
And sorry that we missed it.

Fixed in `v2.5.2`. Can you try it please?

**Comment by litinskii** [comment]
@ilfa  Thanks, all good in v2.5.2
